### ISSUE TITLE
Not reading personal skill config

### ISSUE THREAD

**Issue by builderjer** [OpenVoiceOS/ovos-core#75]
I don't think this actually belongs here, but this is where I am testing now.

When I change the settings in `~/.config/mycroft/skills/<skill_name>`, it is never read.  This seems to be happening on all of the skills, not just this one.

When I use the `settings.json` file which is created with `pip install`, it seems to work fine.

Is this expected behavior? Should I start creating a `settings.json` in all skill folders?

**Comment by JarbasAl** [comment]
@builderjer can you confirm this has been fixed?

**Comment by builderjer** [comment]
I still can't get this to work. Maybe I have something in mycroft.config wrong?

**Comment by builderjer** [comment]
I think this can be closed also.  My skills use the `settings.json` file just fine now
